name: Stand by Pics
favicon: null
layout_spectrum: 0.22359
typography_spectrum: 0.38167
title: Stand by Pics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 1
  lightness: 1
  saturation: 0.5382490276824683
  rhythmicContrast: 1
purpose: []
